source 'https://github.com/CocoaPods/Specs.git'

project 'JotDemo'

platform :ios, '8.0'

target 'JotDemo' do
  pod "jot", :path => "../jot.podspec"
end

target 'JotDemoTests' do
  inherit! :search_paths
  pod 'Specta'
  pod 'Expecta'
  pod 'Expecta+Snapshots'
  pod 'OCMockito'
end
